name: Build-And-Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]


jobs:

  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:         
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Monopoly.Tests/Monopoly.Tests.csproj
          
    - name: Build
      run: dotnet build ./Monopoly.Tests/Monopoly.Tests.csproj --no-restore

    - name: Test
      run: dotnet test ./Monopoly.Tests/Monopoly.Tests.csproj --no-build --logger "html" --results-directory "test_results"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: code/test_results
